<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsXUnit3>true</IsXUnit3>
    <TargetFrameworks>net48;$(BaseTargetFrameworks)</TargetFrameworks>
    <AssemblyTitle>AutoFixture.xUnit.net3.UnitTest</AssemblyTitle>
    <AssemblyName>AutoFixture.Xunit3.UnitTest</AssemblyName>
    <RootNamespace>AutoFixture.Xunit3.UnitTest</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\AutoFixture\AutoFixture.csproj" />
    <ProjectReference Include="..\..\src\AutoFixture.xUnit3\AutoFixture.xUnit3.csproj" />
    <ProjectReference Include="..\TestTypeFoundation\TestTypeFoundation.csproj" />
  </ItemGroup>
</Project>
