using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Xunit.Extensions;
using System.Reflection;
using Ploeh.AutoFixture.Kernel;
using System.Globalization;

namespace Ploeh.AutoFixture.Xunit
{
    /// <summary>
    /// Provides auto-generated data specimens generated by AutoFixture as an extention to
    /// xUnit.net's Theory attribute.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
    [CLSCompliant(false)]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1813:AvoidUnsealedAttributes", Justification = "This attribute is the root of a potential attribute hierarchy.")]
    public class AutoDataAttribute : DataAttribute
    {
        private readonly ICustomizableComposer composer;

        /// <summary>
        /// Initializes a new instance of the <see cref="AutoDataAttribute"/> class.
        /// </summary>
        /// <remarks>
        /// <para>
        /// This constructor overload initializes the <see cref="Composer"/> to an instance of
        /// <see cref="Fixture"/>.
        /// </para>
        /// </remarks>
        public AutoDataAttribute()
            : this(new Fixture())
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AutoDataAttribute"/> class with an
        /// <see cref="ICustomizableComposer"/> of the supplied type.
        /// </summary>
        /// <param name="composerType">The type of the composer.</param>
        /// <exception cref="ArgumentException">
        /// <paramref name="composerType"/> does not implement <see cref="ICustomizableComposer"/>
        /// or does not have a default constructor.
        /// </exception>
        public AutoDataAttribute(Type composerType)
            : this(AutoDataAttribute.CreateComposer(composerType))
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AutoDataAttribute"/> class with the
        /// supplied <see cref="ICustomizableComposer"/>.
        /// </summary>
        /// <param name="composer">The composer.</param>
        public AutoDataAttribute(ICustomizableComposer composer)
        {
            if (composer == null)
            {
                throw new ArgumentNullException("composer");
            }

            this.composer = composer;
        }

        /// <summary>
        /// Gets the composer used by <see cref="GetData"/> to create specimens.
        /// </summary>
        public ICustomizableComposer Composer
        {
            get { return this.composer; }
        }

        /// <summary>
        /// Gets the type of <see cref="Composer"/>.
        /// </summary>
        public Type ComposerType
        {
            get { return this.Composer.GetType(); }
        }

        /// <summary>
        /// Returns the data to be used to test the theory.
        /// </summary>
        /// <param name="methodUnderTest">The method that is being tested</param>
        /// <param name="parameterTypes">The types of the parameters for the test method</param>
        /// <returns>The theory data generated by <see cref="Composer"/>.</returns>
        public override IEnumerable<object[]> GetData(MethodInfo methodUnderTest, Type[] parameterTypes)
        {
            var context = new SpecimenContext(this.composer.Compose());
            var specimens = (from pi in methodUnderTest.GetParameters()
                             select context.Resolve(pi)).ToArray();
            return new[] { specimens };
        }

        private static ICustomizableComposer CreateComposer(Type type)
        {
            if (type == null)
            {
                throw new ArgumentNullException("type");
            }

            if (!typeof(ICustomizableComposer).IsAssignableFrom(type))
            {
                throw new ArgumentException(
                    string.Format(
                        CultureInfo.CurrentCulture,
                        "{0} is not compatible with ICustomizableComposer. Please supply a Type which implements ICustomizableComposer.",
                        type),
                    "type");
            }

            var ctor = type.GetConstructor(Type.EmptyTypes);
            if (ctor == null)
            {
                throw new ArgumentException(
                    string.Format(
                        CultureInfo.CurrentCulture,
                        "{0} has no default constructor. Please supply a a Type that implements ICustomizableComposer and has a default constructor. Alternatively you can supply an ICustomizableComposer instance through one of the AutoDataAttribute constructor overloads. If used as an attribute, this can be done from a derived class.",
                        type),
                    "type");
            }

            return (ICustomizableComposer)ctor.Invoke(null);
        }
    }
}
