<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsXUnit2>true</IsXUnit2>
    <TargetFrameworks>net462;$(BaseTargetFrameworks)</TargetFrameworks>
    <AssemblyTitle>AutoMoq.UnitTest</AssemblyTitle>
    <AssemblyName>AutoFixture.AutoMoq.UnitTest</AssemblyName>
    <RootNamespace>AutoFixture.AutoMoq.UnitTest</RootNamespace>

    <!--  Suppress warning about invalid dependency version in Castle.Core.
          That is a Moq dependency and we cannot fix that somehow. -->
    <NoWarn>$(NoWarn);NU1603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.72" />

    <ProjectReference Include="..\..\src\AutoFixture\AutoFixture.csproj" />
    <ProjectReference Include="..\..\src\AutoMoq\AutoMoq.csproj" />
    <ProjectReference Include="..\TestTypeFoundation\TestTypeFoundation.csproj" />
  </ItemGroup>
</Project>
