<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsXUnit2>true</IsXUnit2>
    <TargetFrameworks>net462;$(BaseTargetFrameworks)</TargetFrameworks>
    <AssemblyTitle>AutoFixture.SeedExtensions.UnitTest</AssemblyTitle>
    <AssemblyName>AutoFixture.SeedExtensions.UnitTest</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AutoFixture.SeedExtensions\AutoFixture.SeedExtensions.csproj" />
    <ProjectReference Include="..\TestTypeFoundation\TestTypeFoundation.csproj" />
  </ItemGroup>
</Project>
