<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsXUnit2>true</IsXUnit2>
    <TargetFrameworks>net462;net48;net5.0;net6.0;net8.0;net10.0</TargetFrameworks>
    <AssemblyTitle>AutoFixture.SeedExtensions.UnitTest</AssemblyTitle>
    <AssemblyName>AutoFixture.SeedExtensions.UnitTest</AssemblyName>
  </PropertyGroup>

  <Choose>
    <When Condition="'$(TargetFramework)'=='net48'">
      <ItemGroup>
        <ProjectReference Include="..\..\src\AutoFixture.SeedExtensions\AutoFixture.SeedExtensions.csproj" SkipGetTargetFrameworkProperties="true" SetTargetFramework="TargetFramework=netstandard2.0" />
        <ProjectReference Include="..\TestTypeFoundation\TestTypeFoundation.csproj" SkipGetTargetFrameworkProperties="true" SetTargetFramework="TargetFramework=netstandard2.0" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <ProjectReference Include="..\..\src\AutoFixture.SeedExtensions\AutoFixture.SeedExtensions.csproj" />
        <ProjectReference Include="..\TestTypeFoundation\TestTypeFoundation.csproj" />
      </ItemGroup>
    </Otherwise>
  </Choose>

</Project>
