<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsXUnit2>true</IsXUnit2>
    <TargetFrameworks>net462;$(BaseTargetFrameworks)</TargetFrameworks>
    <AssemblyTitle>IdiomsUnitTest</AssemblyTitle>
    <AssemblyName>AutoFixture.IdiomsUnitTest</AssemblyName>
    <RootNamespace>AutoFixture.IdiomsUnitTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AutoFixture\AutoFixture.csproj" />
    <ProjectReference Include="..\..\src\Idioms\Idioms.csproj" />
    <ProjectReference Include="..\TestTypeFoundation\TestTypeFoundation.csproj" />
  </ItemGroup>
</Project>
