<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net6.0;net8.0;net10.0</TargetFrameworks>
    <AssemblyTitle>AutoFixture.NUnit4.UnitTest</AssemblyTitle>
    <AssemblyName>AutoFixture.NUnit4.UnitTest</AssemblyName>
    <RootNamespace>AutoFixture.NUnit4.UnitTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="[4.1.0]" />

    <ProjectReference Include="..\..\src\AutoFixture\AutoFixture.csproj" />
    <ProjectReference Include="..\..\src\AutoFixture.NUnit4\AutoFixture.NUnit4.csproj" />
    <ProjectReference Include="..\TestTypeFoundation\TestTypeFoundation.csproj" />
  </ItemGroup>

</Project>
