using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Reflection;
using AutoFixture.Xunit2.Internal;
using Xunit.Sdk;

namespace AutoFixture.Xunit2
{
    /// <summary>
    /// Provides auto-generated data specimens generated by AutoFixture as an extension to
    /// xUnit.net's Theory attribute.
    /// </summary>
    [DataDiscoverer(
        "AutoFixture.Xunit2.NoPreDiscoveryDataDiscoverer",
        "AutoFixture.Xunit2")]
    [AttributeUsage(AttributeTargets.Method)]
    [CLSCompliant(false)]
    [SuppressMessage("Microsoft.Performance", "CA1813:AvoidUnsealedAttributes",
        Justification = "This attribute is the root of a potential attribute hierarchy.")]
    public class AutoDataAttribute : DataAttribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AutoDataAttribute" /> class.
        /// </summary>
        /// <remarks>
        /// <para>
        /// This constructor overload initializes the <see cref="Fixture" /> to an instance of
        /// <see cref="Fixture" />.
        /// </para>
        /// </remarks>
        public AutoDataAttribute()
            : this(() => new Fixture())
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AutoDataAttribute" /> class
        /// with the supplied <paramref name="fixtureFactory" />. Fixture will be created
        /// on demand using the provided factory.
        /// </summary>
        /// <param name="fixtureFactory">The fixture factory used to construct the fixture.</param>
        protected AutoDataAttribute(Func<IFixture> fixtureFactory)
        {
            this.FixtureFactory = fixtureFactory ?? throw new ArgumentNullException(nameof(fixtureFactory));
        }

        /// <summary>
        /// Gets the fixture factory.
        /// </summary>
        public Func<IFixture> FixtureFactory { get; }

        /// <summary>
        /// Returns the data to be used to test the theory.
        /// </summary>
        /// <param name="testMethod">The method that is being tested.</param>
        /// <returns>The theory data generated by <see cref="Fixture" />.</returns>
        public override IEnumerable<object[]> GetData(MethodInfo testMethod)
        {
            if (testMethod is null) throw new ArgumentNullException(nameof(testMethod));

            return new AutoTestCaseSource(this.FixtureFactory)
                .GetTestCases(testMethod).Select(x => x.ToArray()).ToList();
        }
    }
}