<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsXUnit2>true</IsXUnit2>
    <TargetFrameworks>net462;$(BaseTargetFrameworks)</TargetFrameworks>
    <AssemblyTitle>AutoFixtureDocumentationTest</AssemblyTitle>
    <AssemblyName>AutoFixtureDocumentationTest</AssemblyName>
    <RootNamespace>AutoFixtureDocumentationTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AutoFixture\AutoFixture.csproj" />
    <ProjectReference Include="..\..\src\AutoFixture.SeedExtensions\AutoFixture.SeedExtensions.csproj" />
  </ItemGroup>
</Project>
