<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;$(BaseTargetFrameworks)</TargetFrameworks>
    <AssemblyTitle>AutoFakeItEasy</AssemblyTitle>
    <AssemblyName>AutoFixture.AutoFakeItEasy</AssemblyName>
    <RootNamespace>AutoFixture.AutoFakeItEasy</RootNamespace>

    <!-- NuGet options -->
    <PackageId>AutoFixture.AutoFakeItEasy</PackageId>
    <Title>AutoFixture with Auto Mocking using FakeItEasy</Title>
    <Description>This extension turns AutoFixture into an Auto-Mocking Container. The mock instances are created by FakeItEasy. To use it, add the AutoFakeItEasyCustomization to your Fixture instance.</Description>

    <!--  Suppress warning about invalid dependency version in Castle.Core.
          That is FakeItEasy dependency and we cannot fix that somehow. -->
    <NoWarn>$(NoWarn);NU1603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FakeItEasy" Version="[9.0.0,10.0.0)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoFixture\AutoFixture.csproj" />
  </ItemGroup>
</Project>
