<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsXUnit2>true</IsXUnit2>
    <TargetFrameworks>$(BaseTargetFrameworks)</TargetFrameworks>
    <AssemblyTitle>AutoNSubstitute.UnitTest</AssemblyTitle>
    <AssemblyName>AutoFixture.AutoNSubstitute.UnitTest</AssemblyName>
    <RootNamespace>AutoFixture.AutoNSubstitute.UnitTest</RootNamespace>

    <!--  Suppress warning about invalid dependency version in Castle.Core.
          That is NSubstitute dependency and we cannot fix that somehow. -->
    <NoWarn>$(NoWarn);NU1603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" Version="[5.3.0]" />

    <ProjectReference Include="..\..\src\AutoFixture\AutoFixture.csproj" />
    <ProjectReference Include="..\..\src\AutoNSubstitute\AutoNSubstitute.csproj" />
    <ProjectReference Include="..\TestTypeFoundation\TestTypeFoundation.csproj" />
  </ItemGroup>
</Project>
