<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;$(BaseTargetFrameworks)</TargetFrameworks>
    <AssemblyTitle>TestTypeFoundation</AssemblyTitle>
    <AssemblyName>TestTypeFoundation</AssemblyName>

    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
 
</Project>
