using NUnit.Core.Extensibility;

namespace Ploeh.AutoFixture.NUnit.Addins
{
    [NUnitAddin(Name = "AutoTestCaseExtension", Description = "Provides auto-generated data specimens generated by AutoFixture as an extention to NUnit TestCase attribute.", Type = ExtensionType.Core | ExtensionType.Gui | ExtensionType.Client)]
    public class Addin : IAddin
    {
        public bool Install(IExtensionHost host)
        {
            var decorators = host.GetExtensionPoint("TestDecorators");
            if (decorators == null) 
                return false;
            
            decorators.Install(new Reharper.TestDecorator());

            var providers = host.GetExtensionPoint("TestCaseProviders");
            if (providers == null) 
                return false;

            providers.Install(new Builders.AutoTestCaseProvider());

            return true;
        }
    }
}