name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  windows-latest:  
    name: windows-latest
    runs-on: windows-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

        # Read more: https://devblogs.microsoft.com/dotnet/enhanced-security-is-here-with-the-new-trust-publishing-on-nuget-org/  
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: nugetLogin
        with:
          user: ${{ secrets.NUGET_USER }}

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            5.0.x
            6.0.x
            8.0.x
            10.0.x

      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
          
      - name: Run './build.cmd Verify Cover Publish'
        run: ./build.cmd Verify Cover Publish --no-logo
        env:
          NUGET_API_KEY: ${{ steps.nugetLogin.outputs.NUGET_API_KEY }}

      - uses: actions/upload-artifact@v4
        with:
          name: testresults
          path: artifacts/testresults

      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: artifacts/reports

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/packages
